apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateways-ingress
  labels:
    app.kubernetes.io/name: gateways-ingress
spec:
  tls:
  - hosts:
    - ***
    - '***'
    secretName: sas-ingress-certificate-*********
  ingressClassName: nginx
  rules:
  - host: ***
    http:
      paths:
      - path: /scr
        pathType: Prefix
        backend:
          service:
            name: gateways-svc
            port:
              number: 8080
